// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvMsWviArqAArx-wKmM8PM2ZBquuPX1mE',
    appId: '1:136514698895:web:d1e741e50827c8de297afa',
    messagingSenderId: '136514698895',
    projectId: 'web-rtc-flutter-34a8c',
    authDomain: 'web-rtc-flutter-34a8c.firebaseapp.com',
    storageBucket: 'web-rtc-flutter-34a8c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-dp6e1ZwaL0E79dgKBZUyCJ9goL7iUPk',
    appId: '1:136514698895:android:513a1bfe835dd4d7297afa',
    messagingSenderId: '136514698895',
    projectId: 'web-rtc-flutter-34a8c',
    storageBucket: 'web-rtc-flutter-34a8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHD8MnoNwJfowKOdwQEVCtZvPP1-y13tg',
    appId: '1:136514698895:ios:2899b662e9b1aa97297afa',
    messagingSenderId: '136514698895',
    projectId: 'web-rtc-flutter-34a8c',
    storageBucket: 'web-rtc-flutter-34a8c.appspot.com',
    iosBundleId: 'com.example.webRtcFlutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHD8MnoNwJfowKOdwQEVCtZvPP1-y13tg',
    appId: '1:136514698895:ios:2899b662e9b1aa97297afa',
    messagingSenderId: '136514698895',
    projectId: 'web-rtc-flutter-34a8c',
    storageBucket: 'web-rtc-flutter-34a8c.appspot.com',
    iosBundleId: 'com.example.webRtcFlutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvMsWviArqAArx-wKmM8PM2ZBquuPX1mE',
    appId: '1:136514698895:web:8902bf5d732cfa44297afa',
    messagingSenderId: '136514698895',
    projectId: 'web-rtc-flutter-34a8c',
    authDomain: 'web-rtc-flutter-34a8c.firebaseapp.com',
    storageBucket: 'web-rtc-flutter-34a8c.appspot.com',
  );
}
